### PR TITLE
feat: Wip implementation of system_timestep function

### PR DESCRIPTION
**Pull request by christophbeberweil**

### CODE REVIEW

**Comment by christophbeberweil** [comment]
Found it :) If we prevent `gravity_force_vector` from calculating the gravitational force on itself (which should be zero in our model), the NaNs vanish. Apparently, many operations in f64 produce NaN, for instance calcuating the square root of a negative number.

**Review by ThinkerDreamer — APPROVED** [review]
It looks great! Good catch! 😊🙌🏻

**Comment by ThinkerDreamer** [comment]
It's really cool to see some actual output from this! In the failing test (`assert!(false)`) I mean.

**Comment by christophbeberweil** [comment]
More info on the nan rounding: https://users.rust-lang.org/t/watch-out-for-nans/70016

**Pull request merged**
